# Generated by Django 3.0.8 on 2020-08-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(max_length=512)),
                ('origin', models.CharField(max_length=512)),
                ('growth_desc', models.CharField(max_length=2048)),
                ('poisonous_desc', models.CharField(max_length=2048)),
                ('light_desc', models.CharField(max_length=2048)),
                ('watering_desc', models.CharField(max_length=2048)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
