# Generated by Django 3.0.8 on 2020-08-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0002_plants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='growth_desc',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='light_desc',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='origin',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='poisonous_desc',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='scientific_name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='watering_desc',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
