# Generated by Django 3.0.8 on 2020-08-13 01:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0003_auto_20200810_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='growth_desc',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='light_desc',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='poisonous_desc',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='watering_desc',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.CreateModel(
            name='JoinUserPlants',
            fields=[
                ('combo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100)),
                ('watering_freq', models.IntegerField(default=3)),
                ('last_cared_for', models.DateTimeField(default=datetime.datetime.now)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant_tracker.Plants')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
