# Generated by Django 3.0.8 on 2020-08-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0004_auto_20200812_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='light_desc',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='watering_desc',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
